version: '3.7'

services:
  server:
    build: .
    working_dir: /usr/src/app/
    volumes:
      - ./:/usr/src/app
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; yarn dev'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/']
      interval: 600s
      timeout: 10s
      retries: 5
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:14.9
    ports:
      - 5432:5432
    command: postgres -D /var/lib/postgresql/data -F -c logging_collector=on -p 5432
    volumes:
      - ./data/dev:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready "postgresql://postgres:password@db:5432/gif_browser"']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gif_browser
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      PGDATA: /var/lib/postgresql/data
      LOGGING_COLLECTOR: 'on'
    networks:
      - backend
    
networks:
  backend: