import styles from "../styles/Home.module.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import { useEffect, useState } from "react";
import gifs from "../helpers/api/gifs";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [query, setQuery] = useState<string>('');
  const [gifList, setGifList] = useState<any[]>([]);
  const [searchHistory, setSearchHistory] = useState<any[]>([]);
  const [page, setPage] = useState<number>(1);
  const [loading, setLoading] = useState<boolean>(false);
  const [itemsPerPage, setItemsPerPage] = useState<number>(12);
  const [numberOfPages, setNumberOfPages] = useState<number>();

  const executeSearch = async () => {
    setLoading(true);
    const gifResults = await gifs.search({ 
      q: query,
      offset: (page - 1) * itemsPerPage, 
      limit: itemsPerPage
    });

    setNumberOfPages(Math.ceil(gifResults?.pagination?.total_count / itemsPerPage));

    setSearchHistory(gifResults?.searchHistory);
    setGifList(gifResults?.data);
    setLoading(false);
  }
  
  useEffect(() => {
    executeSearch();
  }, [page, itemsPerPage])
  
  const handleSearch = async (e: React.FormEvent) => {
    e.preventDefault();
    setPage(1);
    executeSearch();
  };

  const handlePageChange = (newPage: number) => {
    setPage(newPage);
  };

  const handleItemsPerPageChange = (newItemsPerPage: number) => {
    setItemsPerPage(newItemsPerPage);
    setPage(1);
  };

  const handleClearSearchHistory = async () => {
    await gifs.clearHistory();
    setSearchHistory([]);
  };

  return (
    <>
      <Head>
        <title>GIF Browser</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.content}>
          <h1>Search for GIFs</h1>

          <form onSubmit={handleSearch} className={styles.searchForm}>
            <input
              type="text"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder="Enter your search query"
              className={styles.searchInput}
            />
            <button className={styles.searchButton} type="submit">Search</button>
          </form>

          {loading && <div className={styles.loadingMessage}>Loading...</div>}

          {!loading && gifList?.length > 0 && (
            <div>
              <div className={styles.searchContainer}>
                {gifList.map((gif) => (
                  <img className={styles.gif} key={gif.id} src={gif.images.original.url} />
                ))}
              </div>

              <div className={styles.paginationButtons}>
                <button disabled={page === 1} onClick={() => handlePageChange(page - 1)}>
                  Previous
                </button>
                <span style={{ margin: '10px' }}>{page}/{numberOfPages}</span>
                <button disabled={page === numberOfPages} onClick={() => handlePageChange(page + 1)}>
                  Next
                </button>

                <select value={itemsPerPage} onChange={(e) => handleItemsPerPageChange(Number(e.target.value))} className={styles.itemsPerPageSelector}>
                  <option value={12}>12</option>
                  <option value={24}>24</option>
                  <option value={36}>36</option>
                </select>
              </div>
            </div>
          )}

          {!loading && query && gifList?.length === 0 && (
            <div>
              not found
            </div>
          )}

            <div className={styles.searchHistory}>
              <h2>Search History</h2>
              {searchHistory?.length > 0 ? (
                <ul>
                  {searchHistory?.map((item: any) => (
                    <li key={item.id}>{item.query}</li>
                  ))}
                </ul>
              ) : (
                <div>No search history</div>
              )}
              <button onClick={handleClearSearchHistory} className={styles.cleanSearchHistoryButton}>Clear Search History</button>
            </div>
        </div>

        <div className={styles.grid}></div>
      </main>
    </>
  );
}
